#nama = input('Siapa nama anda? ')
#print('hai ' + nama)
#warna = input('apa warna kesukaanmu? ')
#print('kamu seperti ' + warna)

#tanggal_lahir = input('Tanggal_lahir ')
#print(type(tanggal_lahir))
#umur = 2021 - int(tanggal_lahir)
#print(type(umur))
#print(umur)

berat = input('berat ')
berat_kilo = 0.45 * int(berat)
print(type(berat_kilo))
print(berat_kilo)
